apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  namespace: test-ns
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeappcontainer
      image: 457naveen/node-app-mss
      ports:
      - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodesjsappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 80
      targetPort: 9981
